### ISSUE TITLE
event_type changed

### ISSUE THREAD

**Issue by Netesfiu** [tronikos/google_assistant_sdk_custom#19]
Had to do some debugging since after i've reinstalled the integration my automations stopped working. I don't know if it's a bug or a rewrite, but the `event_type` changed from `google_assistant_sdk_custom_event` to `google_assistant_sdk_custom_custom_event` 
```yaml
event_type: call_service
data:
  domain: google_assistant_sdk_custom
  service: send_text_command
  service_data:
    command: is the ac on
origin: LOCAL
time_fired: "2023-11-24T11:52:25.231174+00:00"
context:
  id: 01HG0JS2CDE17RZKAA8VZA2FGW
  parent_id: null
  user_id: 4dc189dd28ca45c48432cb945f568c77
```

```yaml
event_type: google_assistant_sdk_custom_custom_event
data:
  request: is the ac on
  response: AC is turned off.
origin: LOCAL
time_fired: "2023-11-24T11:52:26.878462+00:00"
context:
  id: 01HG0JS3ZY50872XVNWZQJ1QEQ
  parent_id: null
  user_id: null
```
